/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menwic.dbms.gui;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import menwic.dbms.gui.panels.JPanelEstructuras;
import menwic.dbms.gui.panels.JPanelTuplas;

import menwic.dbms.file_handler.FileHandler;

import menwic.dbms.structure.ListaEstructuras;

/**
 *
 * @author lamr4
 */
public class JFrameFormPrincipal extends javax.swing.JFrame {
    private ListaEstructuras listaEstructuras;
    FileHandler manejador;

    //Constructor
    public JFrameFormPrincipal(ListaEstructuras listaEstructuras) {
        this.listaEstructuras = listaEstructuras; //Lista princiapla para almacenar tablas
        this.manejador = new FileHandler(listaEstructuras); //Manjeador de Archivos de lectura
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCargarArchivo = new javax.swing.JMenuItem();
        itemCargarArchivo1 = new javax.swing.JMenuItem();
        menuEstructura = new javax.swing.JMenu();
        jMenuItemCrudEstructuras = new javax.swing.JMenuItem();
        menuTupla = new javax.swing.JMenu();
        jMenuItemCrudTupla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Base Management System");

        javax.swing.GroupLayout JPanelContenedorLayout = new javax.swing.GroupLayout(JPanelContenedor);
        JPanelContenedor.setLayout(JPanelContenedorLayout);
        JPanelContenedorLayout.setHorizontalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        JPanelContenedorLayout.setVerticalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivo(s)");

        itemCargarArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemCargarArchivo.setText("Cargar Estructura(s)");
        itemCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCargarArchivoActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCargarArchivo);

        itemCargarArchivo1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemCargarArchivo1.setText("Cargar Entrada(s)");
        itemCargarArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCargarArchivo1ActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCargarArchivo1);

        jMenuBar1.add(menuArchivo);

        menuEstructura.setText("Estructura/Tabla");

        jMenuItemCrudEstructuras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCrudEstructuras.setText("Estructuras");
        jMenuItemCrudEstructuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrudEstructurasActionPerformed(evt);
            }
        });
        menuEstructura.add(jMenuItemCrudEstructuras);

        jMenuBar1.add(menuEstructura);

        menuTupla.setText("Tupla/Fila");

        jMenuItemCrudTupla.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCrudTupla.setText("Tupla");
        jMenuItemCrudTupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrudTuplaActionPerformed(evt);
            }
        });
        menuTupla.add(jMenuItemCrudTupla);

        jMenuBar1.add(menuTupla);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCargarArchivoActionPerformed
  //LISTA ENLAZADA DE "FILES"
        JFileChooser selecArchivo = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Etiqueta XML (*.xml, *.dat, *.rpt)", "xml", "dat", "rpt");
        selecArchivo.setFileFilter(filter);

        int resultado = selecArchivo.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) { //Si se Selecciono algun archivo
            String nombreArchivo = selecArchivo.getSelectedFile().getName();
            String rutaArchivo = selecArchivo.getSelectedFile().getAbsolutePath();
            System.out.println("Nombre del archivo seleccionado: " + nombreArchivo);
            System.out.println("Ruta del archivo seleccionado: " + rutaArchivo);

            File archivo = new File(rutaArchivo); //Instancia de Nuevo Archivo(con ruta especificada)
            System.err.println("Se cargo el Archivo al Programa (se creo el File)");
            
            //Arreglar manejador
            manejador.leerEstructuras(archivo); //Metodo encargado de Leer y Gestionar el archivo seleccionado (Estructuras.xml)
            System.err.println("Se termino de Leer el Archivo ");
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ningun Archivo");
            System.out.println("No se seleccionó ningún archivo");
        }
    }//GEN-LAST:event_itemCargarArchivoActionPerformed

    private void jMenuItemCrudTuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrudTuplaActionPerformed
        JPanelTuplas pTuplas = new JPanelTuplas(listaEstructuras);

        pTuplas.setSize(1000, 500);
        pTuplas.setLocation(0, 0);
        JPanelContenedor.removeAll();
        JPanelContenedor.add(pTuplas, BorderLayout.CENTER); //Agrega panel de Menu Tuplas
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }//GEN-LAST:event_jMenuItemCrudTuplaActionPerformed

    private void jMenuItemCrudEstructurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrudEstructurasActionPerformed
        JPanelEstructuras pEstructuras = new JPanelEstructuras(listaEstructuras);

        pEstructuras.setSize(1000, 500);
        pEstructuras.setLocation(0, 0);
        JPanelContenedor.removeAll();
        JPanelContenedor.add(pEstructuras, BorderLayout.CENTER); //Agrega panel de Menu Estructuras
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }//GEN-LAST:event_jMenuItemCrudEstructurasActionPerformed

    private void itemCargarArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCargarArchivo1ActionPerformed
        JFileChooser selecArchivo = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Etiqueta XML (*.xml, *.dat, *.rpt)", "xml", "dat", "rpt");
        selecArchivo.setFileFilter(filter);

        int resultado = selecArchivo.showOpenDialog(null);//Selector de Archivo Dialog

        if (resultado == JFileChooser.APPROVE_OPTION) { //Si se Selecciono algun archivo
            String nombreArchivo = selecArchivo.getSelectedFile().getName();
            String rutaArchivo = selecArchivo.getSelectedFile().getAbsolutePath();
            System.out.println("Nombre del archivo seleccionado: " + nombreArchivo);
            System.out.println("Ruta del archivo seleccionado: " + rutaArchivo);

            File archivo = new File(rutaArchivo); //Instancia de Nuevo Archivo(con ruta especificada)
            System.err.println("Se cargo el Archivo al Programa (se creo el File)");

            //Arreglar manejador
            manejador.leerEntradas(archivo); //Metodo encargado de Leer y Gestionar el archivo seleccionado (Estructuras.xml)
            System.err.println("Se termino de Leer el Archivo ");
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ningun Archivo");
            System.out.println("No se seleccionó ningún archivo");
        }
    }//GEN-LAST:event_itemCargarArchivo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JFrameFormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContenedor;
    private javax.swing.JMenuItem itemCargarArchivo;
    private javax.swing.JMenuItem itemCargarArchivo1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCrudEstructuras;
    private javax.swing.JMenuItem jMenuItemCrudTupla;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEstructura;
    private javax.swing.JMenu menuTupla;
    // End of variables declaration//GEN-END:variables
}
