/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menwic.dbms.gui.panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import menwic.dbms.structure.ListaEstructuras;
import menwic.dbms.structure.NodoEstructura;
import menwic.dbms.structure_fields.Campo;
import menwic.dbms.tools.CreadorDeTupla;
import menwic.dbms.tuple.ListaTuplas;
import menwic.dbms.tuple.Tupla;
import menwic.dbms.values.Valor;

/**
 *
 * @author lamr4
 */
public class JPanelTuplas extends javax.swing.JPanel {

    private final ListaEstructuras listaEstructuras;
    private final CreadorDeTupla creadorDeTupla;
    private DefaultTableModel tablaModel;

    public JPanelTuplas(ListaEstructuras listaEstructuras) {
        this.listaEstructuras = listaEstructuras;
        this.creadorDeTupla = new CreadorDeTupla(this.listaEstructuras);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreTabla = new javax.swing.JTextField();
        jTextFieldTupla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonVerTabla = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("MENU TUPLAS");

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setText("Insertar Fila/Tupla");

        jLabel2.setText("Tupla (Ej = Nit:123, Nombre:Luis...)");

        jTextFieldNombreTabla.setName("txtNombre"); // NOI18N
        jTextFieldNombreTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreTablaActionPerformed(evt);
            }
        });

        jTextFieldTupla.setName("jTextFieldTupla"); // NOI18N
        jTextFieldTupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTuplaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de la tabla");

        jButtonCrear.setText("Crear tupla");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "123456", "20/05/2023", "Quiche"},
                {"124", "123", "21/05/2023", "Xela"},
                {null, null, null, null}
            },
            new String [] {
                "NoFactura", "Nit", "Fecha", "Lugar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneTabla.setViewportView(tabla);

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel10.setText("Tabla / Estructura");

        jButtonVerTabla.setText("Ver Tabla");
        jButtonVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldTupla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)))
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonCrear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVerTabla)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(395, 395, 395))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(221, 221, 221))))
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTupla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCrear)
                            .addComponent(jButtonVerTabla)))
                    .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreTablaActionPerformed

    }//GEN-LAST:event_jTextFieldNombreTablaActionPerformed

    private void jTextFieldTuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTuplaActionPerformed

    }//GEN-LAST:event_jTextFieldTuplaActionPerformed

    /**
     * Envento click en el boton insertar
     *
     * @param evt
     */
    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed

        //extraer los textos de os txt
        String nombreTablaString = this.jTextFieldNombreTabla.getText().trim();
        String tuplaString = this.jTextFieldTupla.getText().trim();

        JOptionPane.showMessageDialog(jPanelContenido,
                this.creadorDeTupla.insertarTupla(nombreTablaString, tuplaString), "Info", JOptionPane.INFORMATION_MESSAGE);
        this.mostrarTabla(nombreTablaString);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTablaActionPerformed
        String nombreTablaString = this.jTextFieldNombreTabla.getText().trim();
        this.mostrarTabla(nombreTablaString);
    }//GEN-LAST:event_jButtonVerTablaActionPerformed

    private void mostrarTabla(String nombreTabla) {
        //mandamos ha buscar el nodo que contiene la tabla
        NodoEstructura tablaEncontrada = this.listaEstructuras.getNodoEstructuraPorNombre(nombreTabla);

        //si el nodod es nulo entonces la tabla no existe
        if (tablaEncontrada == null) {
            JOptionPane.showMessageDialog(null, "Tabla " + nombreTabla + " no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //si existe la tabla entonces mandar ha traer la lista de campos
        Campo[] campos = tablaEncontrada.getEstructura().getListaCampos().returnCampos();
        //mandamos ha crear las columnas
        setColomunas(campos);
        //traemos las tuplas de la lista
        Tupla[] tuplas = tablaEncontrada.getEstructura().getListaTuplas().getTuplas();
        //mandmaos ha mostrar las tuplas
        this.mostrarTuplas(tuplas, campos);
    }

    private void mostrarTuplas(Tupla[] tuplas, Campo[] campos) {
        this.tablaModel.setRowCount(0); //Remueve filas

        //crear un array de strings que sera para agregar cada fila
        String[] fila = new String[campos.length];

        //recorremos cada tupla del array de tuplas
        for (Tupla itemTupla : tuplas) {
            //mandamos ha traer el listado de valores de la tupla
            Valor[] valores = itemTupla.getListaValores().getValores();
            int contador = 0;
            for (Campo campoItem : campos) {

                for (Valor valorItem : valores) {
                    if (campoItem.getNombre().equals(valorItem.getNombreCampo())) {
                        fila[contador] = valorItem.getContenido();
                    }
                }
                contador++;
            }

            this.tablaModel.addRow(fila);//agregamos la fila contruida
            fila = new String[campos.length];//vaciamos la fila para llenarla con una nueva
        }

    }

    private void setColomunas(Campo[] campos) {
        //creamos un nuevo modelo de columnas
        tablaModel = new DefaultTableModel();
        //por cada campo agreagmos una nueva columna
        for (Campo itemCampo : campos) {
            tablaModel.addColumn(itemCampo.getNombre());
        }
        //a la tabla le seteamos un nuevo modelo de columnas
        tabla.setModel(tablaModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonVerTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTextField jTextFieldNombreTabla;
    private javax.swing.JTextField jTextFieldTupla;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
